AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an EC2 instance for the Zelda Soundscapes project

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: "Pick an EC2 size. t2.micro is cheap, great for testing."
  
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing EC2 KeyPair. Needed if I want to SSH in. (Remember to create one in AWS first!)"

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "Just a simple toggle to label environment resources. dev = experiment mode, prod = serious mode!"

Resources:
  MyEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for testing. Allows SSH and HTTP. Probably lock this down for real prod!"
      VpcId: vpc-123456 # I’d normally parameterize this or create a VPC in another template.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Wide open SSH (not ideal, but okay for a quick test)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Let the world see my test page!

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0 # Amazon Linux 2 AMI. Works fine for a test server.
      SecurityGroupIds:
        - !Ref MyEC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "ZeldaSoundscapesInstance-${Environment}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update packages and install Apache right after the instance boots.
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          # Put a friendly message in our web root.
          echo "<h1>Welcome to Zelda Soundscapes - ${Environment} env!</h1>" > /var/www/html/index.html

Outputs:
  InstanceId:
    Description: "EC2 Instance ID, useful if I need to reference it later."
    Value: !Ref MyEC2Instance
  
  PublicIP:
    Description: "Where can I find my instance online? Use this to test in the browser."
    Value: !GetAtt MyEC2Instance.PublicIp
