AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploy an EC2 instance (Amazon Linux 2) in eu-west-1. Parameterized for instance type, key name, and environment.
  Includes an IAM role for AmazonS3ReadOnlyAccess.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: "EC2 instance size"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing EC2 KeyPair in eu-west-1 to allow SSH access"

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "Environment tag (dev or prod)"

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: "/"

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MyIAMRole]
      Path: "/"

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      # AMI for Amazon Linux 2 in eu-west-1 (Ireland):
      ImageId: ami-0f9fc25dd2506cf6d
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub "MyInstance-${Environment}"

Outputs:
  InstanceId:
    Value: !Ref MyInstance
    Description: "EC2 Instance ID"
  PublicIP:
    Value: !GetAtt MyInstance.PublicIp
    Description: "EC2 Public IP"
