AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploy an EC2 instance with parameters for instance type, environment, and key pair.
  Includes an IAM role for S3 read-only access.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: "EC2 instance size"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing KeyPair to allow SSH access"

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "Environment tag"

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: "/"

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MyIAMRole]
      Path: "/"

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-02141377eee7defb9
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub "MyInstance-${Environment}"

Outputs:
  InstanceId:
    Value: !Ref MyInstance
    Description: "EC2 Instance ID"
  PublicIP:
    Value: !GetAtt MyInstance.PublicIp
    Description: "EC2 Public IP"
