AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an EC2 instance for testing

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c55b159cbfafe1f0
      Tags:
        - Key: Name
          Value: ZeldaSoundscapesInstance

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
