name: CI  # Name of the GitHub Actions workflow

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest pdoc cfn-lint awscli bandit

      - name: Lint CloudFormation
        run: cfn-lint IaC/*.yaml

      - name: Validate EC2 template
        run: aws cloudformation validate-template --template-body file://IaC/ec2-instance.yaml --region eu-west-1

      - name: Security scan with Bandit
        run: bandit -r soundscapes tests

      - name: Build and test (Maven)
        run: mvn clean test

      - name: Run tests (unit + performance)
        run: pytest

      - name: Generate docs
        run: pdoc soundscapes --output-dir docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs
