
name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
=======

>>>>>>> ef43be7 (feat: Finalize infrastructure, add performance tests, bandit security checks, docs, and CI updates for eu-west-1)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
<<<<<<< HEAD
      - name: Install dependencies
        run: pip install pytest pdoc cfn-lint
      - name: Lint template
        run: cfn-lint IaC/ec2-instance.yaml
      - name: Validate template
        run: aws cloudformation validate-template --template-body file://IaC/ec2-instance.yaml
      - name: Run tests
        run: python -m pytest
      - name: Generate docs
        run: pdoc soundscapes --output-dir docs

      # Upload docs as a build artifact so they can be viewed on GitHub
      - name: Upload docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs
=======

      - name: Install dependencies
        run: |
          pip install pytest pdoc cfn-lint awscli bandit

      - name: Lint CloudFormation
        run: cfn-lint IaC/*.yaml

      - name: Validate EC2 template
        run: aws cloudformation validate-template --template-body file://IaC/ec2-instance.yaml --region eu-west-1

      - name: Validate S3 template
        run: aws cloudformation validate-template --template-body file://IaC/s3-bucket.yaml --region eu-west-1

      - name: Security scan with bandit
        run: bandit -r soundscapes tests

      - name: Run tests (unit + performance)
        run: pytest
>>>>>>> ef43be7 (feat: Finalize infrastructure, add performance tests, bandit security checks, docs, and CI updates for eu-west-1)
